component: "mysql"
packageName: "mysql-server"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/{{ component }}-{{ env }} token={{ token }} url=http://vault-tools.krrinet.online:8200 validate_certs=false') }}"
